spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/farmdb
    username: farm_user        # replace with your actual DB username
    password: farm_password    # replace with your actual DB password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update          # use 'validate' or 'none' in production
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  thymeleaf:
    cache: false                # disable cache for development
    mode: HTML
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html

  security:
    user:
      name: admin               # fallback in-memory user
      password: admin123        # change in production

server:
  port: 8080

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.security: DEBUG
